blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("post.urls")),
    path('users/', include('accounts.urls')),
    path('tours/', include('tours.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tours/urls.py
import imp
from django.urls import path

from tours import views
urlpatterns = [
    path('', views.get_tour_list, name="tour_list"),
    path('tour/<int:pk>/', views.get_tour_detail, name="tour_detail"),
    path('tour/booking/<int:tour_pk>/', views.create_booking_tour, name="booking")
]

tours/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
# Create your models here.
class Tour(models.Model):
    title = models.CharField("Название",max_length=100)
    image = models.ImageField("Фото",upload_to="tours/")
    description = models.TextField("Описание")
    price = models.DecimalField("Цена",max_digits=10, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField("Активный", default=False)

    class Meta:
        verbose_name = "Тур"
        verbose_name_plural = "Туры"
        ordering = ['-created']

    def __str__(self):
        return self.title


class RegularTour(models.Model):
    TOUR_STATUS_WAITING = 'waiting'
    TOUR_STATUS_START = 'start'
    TOUR_STATUS_COMPLETED = 'completed'
    TOUR_STATUS_REJECTED = 'rejected'
    TOUR_STATUSES = (
        (TOUR_STATUS_WAITING,"Идет набор"),
        (TOUR_STATUS_START, "Начался"),
        (TOUR_STATUS_COMPLETED,"Завершен",),
        (TOUR_STATUS_REJECTED,"Отменен"),
    )
    tour = models.ForeignKey(Tour, on_delete=models.CASCADE)
    start = models.DateTimeField("Начало")
    end = models.DateTimeField("Конец")
    places_count = models.PositiveSmallIntegerField("Количество мест")
    status = models.CharField(
        "Статус", 
        choices=TOUR_STATUSES, 
        default=TOUR_STATUS_WAITING,
        max_length=10
        )

    class Meta:
        verbose_name = "Регуларный тур"
        verbose_name_plural = "Регуларный туры"
        ordering = ['-start']


    def __str__(self):
        return f"{self.tour.title}-{self.start.date()}"

        
class TourBooking(models.Model):
    STATUS_NEW = "new"
    STATUS_CONFIRMED = "confirmed"
    STATUS_FINISHED = "finished"
    STATUS_REJECTED = "rejected"
    BOOKING_STATUSES = (
        (STATUS_NEW, "Новый"),
        (STATUS_CONFIRMED,"Подтвержден"),
        (STATUS_FINISHED, "Завершен",),
        (STATUS_REJECTED, "Отменен",)
    )
    user = models.ForeignKey(
        User, 
        on_delete=models.DO_NOTHING
        )
    regular_tour = models.ForeignKey(
        RegularTour,
        on_delete=models.DO_NOTHING
    )
    place_count = models.PositiveSmallIntegerField("Места")
    mobile = models.CharField("Номер телефона", max_length=10)
    status = models.CharField(
        "Статус",
        max_length=9,
        choices=BOOKING_STATUSES,
        default=STATUS_NEW 
    )
    is_paid = models.BooleanField("Оплачено", default=False)
    notice = models.CharField(
        "Доп. инфо", 
        max_length=255,
        null=True, 
        blank=True
    )

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    class Meta:
        verbose_name = "Бронирование"
        verbose_name_plural = "Бронирования"
        ordering = ["-created"]

    def __str__(self):
        return f"Бронь {self.id}"

tours/forms.py
from django import forms

from tours.models import TourBooking, RegularTour



class TourBookingForm(forms.ModelForm):
    regular_tour = forms.ModelChoiceField(
        queryset=RegularTour.objects.filter(status=RegularTour.TOUR_STATUS_WAITING),
        widget=forms.Select(attrs={"class":"form-control"})
    )
    
    class Meta:
        model = TourBooking
        fields = ["regular_tour","place_count", "mobile", "notice"]
        widgets = {
            "place_count": forms.NumberInput(attrs={
                "class":"form-control"
            }),
            "mobile":forms.TextInput(attrs={
                "class":"form-control"
            }),
            "notice":forms.TextInput(attrs={
                "class":"form-control"
            }),
        }

tours/views.py
from django.shortcuts import render, redirect

# Create your views here.
from tours.models import Tour, RegularTour
from django.http import Http404
from tours.forms import TourBookingForm
from tours.utils import minus_place_count


def get_tour_list(request):
    tours = Tour.objects.filter(is_active=True)
    context = {
        "tours":tours,
    }
    return render(request, 'tour_list.html', context=context)


def get_tour_detail(request, pk):
    try:
        tour = Tour.objects.get(id=pk)
    except Tour.DoesNotExist: 
        raise Http404   

    form = TourBookingForm()
    context ={
        "tour":tour,
        "form":form
    }
    return render(request, 'tour_detail.html', context)




def create_booking_tour(request, tour_pk):  
    if request.method == "POST": 
        form = TourBookingForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            print(data)
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            minus_place_count(
                data["regular_tour"].id, 
                data["place_count"]
                )
            return redirect("tour_detail", pk=tour_pk)
    else:
        print("asdasd")
        return redirect("tour_detail", pk=tour_pk)

tours/templates/tour_detail.html
{% extends 'base.html' %}

{% block title %}
  {{tour.title}}
{% endblock %}


{% block content %}
    <section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url('/static/images/blog_bg.jpg');" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
      <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
        <div class="col-md-9 ftco-animate pb-5 text-center">
          <h1 class="mb-3 bread">{{tour.title}}</h1>
          <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a href="blog.html">Blog <i class="ion-ios-arrow-forward"></i></a></span> <span>Blog Single <i class="ion-ios-arrow-forward"></i></span></p>
        </div>
      </div>
    </div>
  </section>

  <section class="ftco-section ftco-no-pt ftco-no-pb">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 order-md-last ftco-animate py-md-5 mt-md-5">
          <h2 class="mb-3">{{tour.title}}</h2>
          <h3 class="mb-3">Цена тура: {{ tour.price }}сом</h3>
          <p>
            <img src="{{tour.image.url}}" alt="" class="img-fluid">
          </p>
          <p>{{tour.description}}</p>

        
        <div class="list-group">
            {% for regular_tour in tour.regulartour_set.all %}
                <a href="#" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Начало: {{regular_tour.start|date:"d.m.Y H:i"}}</h5>
                    <h5 class="mb-1">Конец:{{regular_tour.end|date:"d.m.Y H:i"}} </h5>
                    <small>Количество мест: {{ regular_tour.places_count }}</small>
                </div>
                <p class="mb-1">Some placeholder content in a paragraph.</p>
                <button type="button" data-id="{{regular_tour.id}}" class="btn btn-warning" data-toggle="modal" data-target="#tour_modal">
                  Забронировать
                </button>
                </a>
            {% empty %}
                <h3 style="border:1px solid black;">
                    Регулярных туров нет
                </h3>
            {% endfor %}
        </div>
        </div>

      </div>
    </div>
  </section> <!-- .section -->

  <div class="modal fade" id="tour_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Бронирование тура</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form method="post" action="{% url 'booking' tour.pk  %}">
        <div class="modal-body">
            {% csrf_token %}
            {{ form }}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
          <button type="submit" class="btn btn-primary">Забронировать</button>
        </div>
      </form>
      </div>
    </div>
  </div>
  

{% endblock %}

tours/templates/tour_list.html
{% extends 'base.html' %}

{% block title %}
  Туры
{% endblock %}

{% block content %}
<section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url('/static/images/tour_bg.jpeg');" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
      <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
        <div class="col-md-9 ftco-animate pb-5 text-center">
          <h1 class="mb-3 bread">Places to Travel</h1>
          <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>About us <i class="ion-ios-arrow-forward"></i></span></p>
        </div>
      </div>
    </div>
  </section>

  <section class="ftco-section">
      <div class="container">
          <div class="row justify-content-center pb-4">
        <div class="col-md-12 heading-section text-center ftco-animate">
          <h2 class="mb-4">Best Place Destination</h2>
        </div>
      </div>
      <div class="row">
          <div class="col-md-3 ftco-animate">
              <div class="project-destination">
                  <a href="#" class="img" style="background-image: url(images/place-1.jpg);">
                      <div class="text">
                          <h3>Singapore</h3>
                          <span>8 Tours</span>
                      </div>
                  </a>
              </div>
          </div>
          <div class="col-md-3 ftco-animate">
              <div class="project-destination">
                  <a href="#" class="img" style="background-image: url(images/place-2.jpg);">
                      <div class="text">
                          <h3>Canada</h3>
                          <span>2 Tours</span>
                      </div>
                  </a>
              </div>
          </div>
          <div class="col-md-3 ftco-animate">
              <div class="project-destination">
                  <a href="#" class="img" style="background-image: url(images/place-3.jpg);">
                      <div class="text">
                          <h3>Thailand</h3>
                          <span>5 Tours</span>
                      </div>
                  </a>
              </div>
          </div>
          <div class="col-md-3 ftco-animate">
              <div class="project-destination">
                  <a href="#" class="img" style="background-image: url(images/place-4.jpg);">
                      <div class="text">
                          <h3>Autralia</h3>
                          <span>5 Tours</span>
                      </div>
                  </a>
              </div>
          </div>
      </div>
      </div>
  </section>

  <section class="ftco-section ftco-no-pb ftco-no-pt">
      <div class="container">
          <div class="row">
                  <div class="col-md-12 mb-5">
                      <div class="search-wrap-1 search-wrap-notop ftco-animate p-4">
                          <form action="#" class="search-property-1">
                      <div class="row">
                          <div class="col-lg align-items-end">
                              <div class="form-group">
                                  <label for="#">Destination</label>
                                <div class="form-field">
                                    <div class="icon"><span class="ion-ios-search"></span></div>
                              <input type="text" class="form-control" placeholder="Search place">
                            </div>
                        </div>
                          </div>
                          <div class="col-lg align-items-end">
                              <div class="form-group">
                                  <label for="#">Check-in date</label>
                                  <div class="form-field">
                                    <div class="icon"><span class="ion-ios-calendar"></span></div>
                              <input type="text" class="form-control checkin_date" placeholder="Check In Date">
                            </div>
                        </div>
                          </div>
                          <div class="col-lg align-items-end">
                              <div class="form-group">
                                  <label for="#">Check-out date</label>
                                  <div class="form-field">
                                    <div class="icon"><span class="ion-ios-calendar"></span></div>
                              <input type="text" class="form-control checkout_date" placeholder="Check Out Date">
                            </div>
                        </div>
                          </div>
                          <div class="col-lg align-items-end">
                              <div class="form-group">
                                  <label for="#">Price Limit</label>
                                  <div class="form-field">
                                    <div class="select-wrap">
                            <div class="icon"><span class="ion-ios-arrow-down"></span></div>
                            <select name="" id="" class="form-control">
                              <option value="">$5,000</option>
                              <option value="">$10,000</option>
                              <option value="">$50,000</option>
                              <option value="">$100,000</option>
                              <option value="">$200,000</option>
                              <option value="">$300,000</option>
                              <option value="">$400,000</option>
                              <option value="">$500,000</option>
                              <option value="">$600,000</option>
                              <option value="">$700,000</option>
                              <option value="">$800,000</option>
                              <option value="">$900,000</option>
                              <option value="">$1,000,000</option>
                              <option value="">$2,000,000</option>
                            </select>
                          </div>
                            </div>
                        </div>
                          </div>
                          <div class="col-lg align-self-end">
                              <div class="form-group">
                                  <div class="form-field">
                              <input type="submit" value="Search" class="form-control btn btn-primary">
                            </div>
                        </div>
                          </div>
                      </div>
                  </form>
              </div>
                  </div>
          </div>
      </div>
  </section>


  <section class="ftco-section ftco-no-pt">
      <div class="container">
          <div class="row justify-content-center pb-4">
        <div class="col-md-12 heading-section text-center ftco-animate">
          <h2 class="mb-4">Туры</h2>
        </div>
      </div>
      <div class="row">
          {% for tour in tours %}
            <div class="col-md-4 ftco-animate">
              <div class="project-wrap">
                  <a href="{% url 'tour_detail' tour.id %}" class="img" style="background-image: url({{tour.image.url}});"></a>
                  <div class="text p-4">
                      <span class="price">{{tour.price}}сом</span>
                      <span class="days">8 Days Tour</span>
                      <h3><a href="{% url 'tour_detail' tour.id %}">{{ tour.title }}</a></h3>
                      <p class="location"><span class="ion-ios-map"></span> Bali, Indonesia</p>
                      <!-- <ul>
                          <li><span class="flaticon-shower"></span>2</li>
                          <li><span class="flaticon-king-size"></span>3</li>
                          <li><span class="flaticon-mountains"></span>Near Mountain</li>
                      </ul> -->
                  </div>
              </div>
            </div>
          {% endfor %}
      </div>
      <div class="row mt-5">
        <div class="col text-center">
          <div class="block-27">
            <ul>
              <li><a href="#">&lt;</a></li>
              <li class="active"><span>1</span></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li><a href="#">5</a></li>
              <li><a href="#">&gt;</a></li>
            </ul>
          </div>
        </div>
      </div>
      </div>
  </section>


{% endblock %}